### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=IntelliJ IDEA

### 分页查询员工信息
POST http://localhost:8080/emp/queryEmployees
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50SWQiOjEwMiwiaXNBZG1pbiI6dHJ1ZSwiaWF0IjoxNzU1Njk4OTI3LCJleHAiOjE3NTU3MDYxMjd9.aGzj1NfrZ6tHj0LDtwp0sWsW4rWie4Ikd9Pb3DzkvOKOqBEK0L05LrgDwa0306mkomHbMp4nBe1Nyzev0bTnrA

{
  "pageNum": "",
  "pageSize": "",
  "deptId": "",
  "isActive": "",
  "isManager": "",
  "empName": ""
}

### 修改员工信息
POST http://localhost:8080/emp/updateEmployeeInfo
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50SWQiOjEwMiwiaXNBZG1pbiI6dHJ1ZSwiaWF0IjoxNzU1Nzc5MDk0LCJleHAiOjE3NTU3ODYyOTR9.76KoodQaU31W3f1s6MriyvV78EwwX3zTi_teXJDNJ5zsNlR4qH_GgEw8Efwyg7qCiCWNqLuARdF-mnJ82efITA

{
  "empId": 10006,
  "empName": "张玩玩",
  "deptId": 10001,
  "position": "人力部",
  "phone": "19328516903",
  "email": "string@ss.com",
  "idCard": "951176183105097299"
}



