### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=IntelliJ IDEA

### 分页查询员工信息
POST http://localhost:8080/emp/queryEmployees
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50SWQiOjEwMiwiaXNBZG1pbiI6dHJ1ZSwiaWF0IjoxNzU1Njk4OTI3LCJleHAiOjE3NTU3MDYxMjd9.aGzj1NfrZ6tHj0LDtwp0sWsW4rWie4Ikd9Pb3DzkvOKOqBEK0L05LrgDwa0306mkomHbMp4nBe1Nyzev0bTnrA

{
  "pageNum": "",
  "pageSize": "",
  "deptId": "",
  "isActive": "",
  "isManager": "",
  "empName": ""
}

### 修改员工信息
#POST http://localhost:8080/emp/updateEmployeeInfoRequest
POST http://localhost:8080/emp/updateEmployeeInfo
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50SWQiOjEwMDA4LCJpc0FkbWluIjpmYWxzZSwiaWF0IjoxNzU2Mzk3MDE1LCJleHAiOjE3NTY0MDQyMTV9.0TBochCvR0rcix0DMNWXtyA6_xga-gULm6bmwIoCTlVzpLxJxMK6hmfVDECuB8UEH--HZERss7GUSjTjbqvjvA

{
  "empId": 10006,
  "empName": "张玩玩",
  "deptId": 10001,
  "position": "人力部",
  "phone": "19328516903",
  "email": "string@ss.com",
  "idCard": "951176183105097299"
}

### 获取同部门信息
POST http://localhost:8080/emp/getSimpleDeptEmp
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50SWQiOjEwMDAzLCJpc0FkbWluIjpmYWxzZSwiaWF0IjoxNzU2NTI0OTY3LCJleHAiOjE3NTY1MzIxNjd9.d3bWRdSAVNOgeOSPj9cAktZCkyw-mBv4eBwmp0UU72GtgGpmhSI5g6DyaTp2G8TVq_k3ysMG78X4twaQrrRVTQ


### 获取全部员工简单信息
POST http://localhost:8080/emp/getAllSimpleEmp
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50SWQiOjEwMiwiaXNBZG1pbiI6dHJ1ZSwiaWF0IjoxNzU2ODY5NDgwLCJleHAiOjE3NTY4NzY2ODB9.04-3zcyBqX-mDbzoMKH2QaDULLZaDgApJr_2Q4l09GKlqh1Je1s4k_boHGw3AEVyWKHtwDVFFYrYpbUzTWbJvQ



