### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=IntelliJ IDEA

### 上传会议室图片
POST http://localhost:8080/meetingRoom/uploadImage
Content-Type: multipart/form-data; boundary=MyBoundary
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50SWQiOjEwMiwiaXNBZG1pbiI6dHJ1ZSwiaWF0IjoxNzU2MTA1MTc2LCJleHAiOjE3NTYxMTIzNzZ9.cSTPvD2-Qc0ip2EFbMxcwFtXPMcoeaca1KJy34tMEsaoYsWC8aoDDt9Ym2jw2JxWubIuw9wHVIZOZt-Pm54mDw

--MyBoundary
Content-Disposition: form-data; name="imageFile"; filename="meeting-room.jpg"
Content-Type: image/jpeg

< /Users/yhcm/Desktop/b_cd9547362b6816ff1ea04a7474885165.jpg
#< /Users/yhcm/Desktop/TXT.txt
--MyBoundary--


### 新增会议室
POST http://localhost:8080/meetingRoom/addMeetingRoom
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50SWQiOjEwMiwiaXNBZG1pbiI6dHJ1ZSwiaWF0IjoxNzU2MTEyODc3LCJleHAiOjE3NTYxMjAwNzd9.M7EuyBM5dkf4YuzlAqQajxptvutVT0cJFaZQ324hxKYugxTXfZVCxOsdHJ1KOEyVW_xry3RUNhMO6treRj3oSA

{
  "roomName": "小型会议室111",
  "roomType": "SMALL",
  "capacity": 99,
  "location": "天上云间1层",
  "roomStatus": "MAINTENANCE",
  "imageUrl": "/resources/2298f7bb-a3d1-43bf-9ca6-2f36a2e1466c.jpg",
  "equipmentIds": [10001, 10003, 10005, 10007]
}

### 分页查询会议室
POST http://localhost:8080/meetingRoom/queryMeetingRooms
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50SWQiOjEwMiwiaXNBZG1pbiI6dHJ1ZSwiaWF0IjoxNzU2MTA1MTc2LCJleHAiOjE3NTYxMTIzNzZ9.cSTPvD2-Qc0ip2EFbMxcwFtXPMcoeaca1KJy34tMEsaoYsWC8aoDDt9Ym2jw2JxWubIuw9wHVIZOZt-Pm54mDw

{
  "pageNum": 1,
  "pageSize": 30,
  "roomName": "",
  "roomType": "",
  "minCapacity": null,
  "maxCapacity": 20,
  "location": "2",
  "roomStatus": "",
  "equipmentIdList": [10001]
}



### 通过会议室id获取设备集合
POST http://localhost:8080/meetingRoom/getRoomEquipmentList
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50SWQiOjEwMDAxLCJpc0FkbWluIjpmYWxzZSwiaWF0IjoxNzU2MTE0Mjc0LCJleHAiOjE3NTYxMjE0NzR9.Gd7v41pK5rYfHqWdHeGink_G-QTnVVhgL01_B-L5GSItwCGwz64hj9HzDRvp_-hrAc2fQSy0xB0gdM-WEQ4qnA

10014