### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=IntelliJ IDEA

### 上传会议室图片
POST http://localhost:8080/meetingRoom/uploadImage
Content-Type: multipart/form-data; boundary=MyBoundary
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50SWQiOjEwMiwiaXNBZG1pbiI6dHJ1ZSwiaWF0IjoxNzU2MTMzNzU3LCJleHAiOjE3NTYxNDA5NTd9.cxprAUGTjhzYyzfh0VHbtdhCXrx1ZeAzosgiS1Muo8iLTMTDklID4Ba14Y3Jv79TWq1sSN8uaL14jJG-PxgdAA

--MyBoundary
Content-Disposition: form-data; name="imageFile"; filename="meeting-room.jpg"
Content-Type: image/jpeg

< /Users/yhcm/Desktop/QQ20250220-143949.png
#< /Users/yhcm/Desktop/TXT.txt
--MyBoundary--


### 新增会议室
POST http://localhost:8080/meetingRoom/addMeetingRoom
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50SWQiOjEwMiwiaXNBZG1pbiI6dHJ1ZSwiaWF0IjoxNzU2MTEyODc3LCJleHAiOjE3NTYxMjAwNzd9.M7EuyBM5dkf4YuzlAqQajxptvutVT0cJFaZQ324hxKYugxTXfZVCxOsdHJ1KOEyVW_xry3RUNhMO6treRj3oSA

{
  "roomName": "小型会议室111",
  "roomType": "SMALL",
  "capacity": 99,
  "location": "天上云间1层",
  "roomStatus": "MAINTENANCE",
  "imageUrl": "/resources/2298f7bb-a3d1-43bf-9ca6-2f36a2e1466c.jpg",
  "equipmentIds": [10001, 10003, 10005, 10007]
}

### 分页查询会议室
POST http://localhost:8080/meetingRoom/queryMeetingRooms
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50SWQiOjEwMiwiaXNBZG1pbiI6dHJ1ZSwiaWF0IjoxNzU2MTMyMjE4LCJleHAiOjE3NTYxMzk0MTh9.P00uRiiBYG35JlLv-uWsXWs1pvVLtQOrrQiVWfp67i7_muXCFXFM3UzEXDgU10BeHI-89upYVUdRWAMflEJQNQ

{
  "pageNum": 1,
  "pageSize": 30,
  "roomName": "",
  "roomType": "",
  "minCapacity": null,
  "maxCapacity": null,
  "location": "2",
  "roomStatus": "",
  "equipmentIdList": []
}



### 通过会议室id获取设备集合
POST http://localhost:8080/meetingRoom/getRoomEquipmentList
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50SWQiOjEwMiwiaXNBZG1pbiI6dHJ1ZSwiaWF0IjoxNzU2MTMyNzM1LCJleHAiOjE3NTYxMzk5MzV9.WNQ5iIJurk35wmTQIVl8OL05dpXXvt7KsY5DFHAavRMwvsVyRtGckt5NQbWuGD8PGuh7Vqr9GIZyfcgf9MgnLg

10002


### 修改会议室
POST http://localhost:8080/meetingRoom/updateMeetingRoom
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50SWQiOjEwMiwiaXNBZG1pbiI6dHJ1ZSwiaWF0IjoxNzU2MTMzNzU3LCJleHAiOjE3NTYxNDA5NTd9.cxprAUGTjhzYyzfh0VHbtdhCXrx1ZeAzosgiS1Muo8iLTMTDklID4Ba14Y3Jv79TWq1sSN8uaL14jJG-PxgdAA

{
  "roomId": 10002,
  "roomName": "小452会议12",
  "roomType": "LARGE",
  "capacity": 5,
  "location": "D栋2层202",
  "roomStatus": "DISABLED",
  "imageUrl": "/resources/fb4998c6-5bcd-49cc-8da3-84f157ded15b.jpg",
  "equipmentIds": [10004, 10007, 10003]
}