### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=IntelliJ IDEA

### 登录
POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "accountId": "102",
  "password": "123456"
}

### 登录
POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "accountId": "10001",
  "password": "123456"
}

### 退出登录
POST http://localhost:8080/auth/logout
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50SWQiOjEwMiwiaXNBZG1pbiI6dHJ1ZSwiaWF0IjoxNzU1NzkxMzcwLCJleHAiOjE3NTU3OTg1NzB9.n2Vdrz5NT8neRei1kpOr5VtyMSh4GVxWjtgxJ4itqPCFsj5qYUoFicTnApW-bfYaZQLUr5paWJwhwZvCA_GICw


### 注册
POST http://localhost:8080/auth/register
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50SWQiOjEwMiwiaXNBZG1pbiI6dHJ1ZSwiaWF0IjoxNzU1NDk0MjQ4LCJleHAiOjE3NTU1MDE0NDh9.Tn0ZuOtVWOCT7I2jZZSfjhBlQ0XY1_3DERuTMxvbpt_2M_dxq9XobeneCvXk1mxYVrCEGCkYYtOUKoDc2hey7g

{
  "empName": "null",
  "deptId": 10003,
  "phone": "18888788436",
  "idCard": "430420199808080737",
  "password": "123456",
  "position": "超神",
  "email": "33@qq.com",
  "isManager": false
}

### 分页查询员工信息
POST http://localhost:8080/emp/queryEmployees
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50SWQiOjEwMiwiaXNBZG1pbiI6dHJ1ZSwiaWF0IjoxNzU1Njk4OTI3LCJleHAiOjE3NTU3MDYxMjd9.aGzj1NfrZ6tHj0LDtwp0sWsW4rWie4Ikd9Pb3DzkvOKOqBEK0L05LrgDwa0306mkomHbMp4nBe1Nyzev0bTnrA

{
  "pageNum": "",
  "pageSize": "",
  "deptId": "",
  "isActive": "",
  "isManager": "",
  "empName": ""
}

### 修改账号状态
POST http://localhost:8080/account/toggleAccountStatus
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50SWQiOjEwMiwiaXNBZG1pbiI6dHJ1ZSwiaWF0IjoxNzU1Njk4OTI3LCJleHAiOjE3NTU3MDYxMjd9.aGzj1NfrZ6tHj0LDtwp0sWsW4rWie4Ikd9Pb3DzkvOKOqBEK0L05LrgDwa0306mkomHbMp4nBe1Nyzev0bTnrA

100010

### 修改员工信息
POST http://localhost:8080/emp/updateEmployeeInfo
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50SWQiOjEwMiwiaXNBZG1pbiI6dHJ1ZSwiaWF0IjoxNzU1Nzc5MDk0LCJleHAiOjE3NTU3ODYyOTR9.76KoodQaU31W3f1s6MriyvV78EwwX3zTi_teXJDNJ5zsNlR4qH_GgEw8Efwyg7qCiCWNqLuARdF-mnJ82efITA

{
  "empId": 10006,
  "empName": "张玩玩",
  "deptId": 10001,
  "position": "人力部",
  "phone": "19328516903",
  "email": "string@ss.com",
  "idCard": "951176183105097299"
}

### 重置密码
POST http://localhost:8080/account/resetPassword
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50SWQiOjEwMiwiaXNBZG1pbiI6dHJ1ZSwiaWF0IjoxNzU1NzQzMjI2LCJleHAiOjE3NTU3NTA0MjZ9._kvu4QkQ68zMxNBP6RuKe51UmajtXGZ0z2dFvfCJJmzpHeBebtmfq6R3eSerqXFn56YOXLixq7TYlIycrogHzg

10001

### 修改密码
POST http://localhost:8080/account/changePassword
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50SWQiOjEwMiwiaXNBZG1pbiI6dHJ1ZSwiaWF0IjoxNzU1ODcxOTA4LCJleHAiOjE3NTU4NzkxMDh9.5BCA4wJB_PL6xjbf63HxXaaqZgataxHChDkSQrb4qVxScgQtNtR3Zy3LRoYD5ObF0gDwvUEM64ikmf6dO87omg

{
  "oldPassword": "123456",
  "newPassword": "111",
  "confirmPassword": "111"
}

### 获取账号信息详情
POST http://localhost:8080/account/getAccountDetail
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50SWQiOjEwMDAxLCJpc0FkbWluIjpmYWxzZSwiaWF0IjoxNzU1ODc0MDA0LCJleHAiOjE3NTU4ODEyMDR9.XX6r8o1BFb90oKEMEQbYnzMrp95Avf1W5Mc-cO2uQKDVq7EMscywjLN-qoDLXweQnMiKts-p2aJ6iKds595SyQ




