### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=IntelliJ IDEA

### 会议室预约
POST http://localhost:8080/res/reservation
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50SWQiOjEwMDA4LCJpc0FkbWluIjpmYWxzZSwiaWF0IjoxNzU2ODE1MDMxLCJleHAiOjE3NTY4MjIyMzF9.1MvLmygUK018YvQE4e6Py4Wz_FyLBpncvhR-48KXBTI271ntJ2CbVmC7I21iYPJbXkg5hvv_EsGo0l9g2lKCKw

{
  "roomId": 10007,
  "meetingTopic": "测试会议",
  "meetingDesc": "测试会议详情",
  "reservationDate": "2025-09-03",
  "startTime": "09:30",
  "endTime": "12:00",
  "attendees": [],
  "mentionAll": true
}

### 查询预约信息集合
POST http://localhost:8080/res/queryReservations
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50SWQiOjEwMDA4LCJpc0FkbWluIjpmYWxzZSwiaWF0IjoxNzU2ODE1MDMxLCJleHAiOjE3NTY4MjIyMzF9.1MvLmygUK018YvQE4e6Py4Wz_FyLBpncvhR-48KXBTI271ntJ2CbVmC7I21iYPJbXkg5hvv_EsGo0l9g2lKCKw

{
  "pageNum": null,
  "pageSize": null,
  "accountId": 10001,
  "reservationDate": null,
  "reservationStatus": null
}

### 修改预约状态
POST http://localhost:8080/res/updateReservation
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50SWQiOjEwMDA4LCJpc0FkbWluIjpmYWxzZSwiaWF0IjoxNzU2ODE1MDMxLCJleHAiOjE3NTY4MjIyMzF9.1MvLmygUK018YvQE4e6Py4Wz_FyLBpncvhR-48KXBTI271ntJ2CbVmC7I21iYPJbXkg5hvv_EsGo0l9g2lKCKw

{
  "reservationId": 10007,
  "reservationStatus": "CANCELLED",
  "rejectReason": "213",
  "approvalAccountId": 123
}

### 修改预约状态
POST http://localhost:8080/res/updateReservation
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50SWQiOjEwMiwiaXNBZG1pbiI6dHJ1ZSwiaWF0IjoxNzU2ODE1MDM1LCJleHAiOjE3NTY4MjIyMzV9.XDEdnlp2k5lkG9S98K_Wmbg31rmzUB9LhtAsPiRUzuGnfrqpCzDVqsK8CQbKBJj8wcwFCA9kxPuyKb0vdHC-nA

{
  "reservationId": 10010,
  "reservationStatus": "APPROVED",
  "rejectReason": "我拒绝同意，不要问为什么",
  "approvalAccountId": 123
}



