### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=IntelliJ IDEA

### 获取会议室可用状态 Obsolete
POST http://localhost:8080/roomAvail/getRoomAvailability
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50SWQiOjEwMiwiaXNBZG1pbiI6dHJ1ZSwiaWF0IjoxNzU2MTc2MzkwLCJleHAiOjE3NTYxODM1OTB9.-i62ErBP6Dy9HkgkjKGoF5GeB8dgYoOe_PlbeKKBd9y7PSYG1jOhsQTfp8oTGL4u8xuEOkS-2N-8CGhk6atO0A

10002


### 获取会议室可用日期
POST http://localhost:8080/roomAvail/getRoomAvailDateList
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50SWQiOjEwMDA4LCJpc0FkbWluIjpmYWxzZSwiaWF0IjoxNzU2NDM4MjM1LCJleHAiOjE3NTY0NDU0MzV9.nw6TFlu2xZBt31eqns3sBEpM9TzHD5QgijMUZrBAYhv2oCNewrEwQYCRUHDc7lny-TYoev4oAdLnuRyzImJ78Q

10011


### 获取所有预约时间段
POST http://localhost:8080/roomAvail/getAllTimeSlotList
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50SWQiOjEwMDAxLCJpc0FkbWluIjpmYWxzZSwiaWF0IjoxNzU2Mjk3NzE2LCJleHAiOjE3NTYzMDQ5MTZ9.C4Y51Km0IHBhuFhHdiBFogYMgHWj_BwZjXoK6Vvp--kor403TkBW4EejZUsvphN6N5a-jKoKtA0I4EHoJoFbkQ


### 获取可用预约时间段
POST http://localhost:8080/roomAvail/getRoomAvailTimeSlotList
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50SWQiOjEwMDAzLCJpc0FkbWluIjpmYWxzZSwiaWF0IjoxNzU2NTI0OTY3LCJleHAiOjE3NTY1MzIxNjd9.d3bWRdSAVNOgeOSPj9cAktZCkyw-mBv4eBwmp0UU72GtgGpmhSI5g6DyaTp2G8TVq_k3ysMG78X4twaQrrRVTQ

{
  "roomId": 10003,
  "date": "2025-09-05"
}
