DROP SEQUENCE IF EXISTS dept_seq;
DROP SEQUENCE IF EXISTS user_seq;

-- 部门 ID 序列
CREATE SEQUENCE dept_seq START WITH 10001;

-- 账号 ID 序列
CREATE SEQUENCE account_seq START WITH 10001;

-- 用户 ID 序列
CREATE SEQUENCE emp_seq START WITH 10001; -- 员工工号/员工账号序列，从10001开始
CREATE SEQUENCE admin_seq START WITH 101; -- 管理员账号序列，从101开始